#!/bin/bash
set -euo pipefail

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
CGO_ENABLED=0 GOOS=linux GOARCH="${ARCH:-amd64}" \
    go build -trimpath -buildvcs=false -mod=mod -tags netgo \
    -ldflags "-s -w -buildid= -X main.VERSION=$VERSION" \
    -o bin/kubernetes-agent .
