#!/bin/bash
set -euo pipefail

if [[ -n "${DAPPER_UID:-}" && -n "${DAPPER_GID:-}" ]]; then
    trap 'chown -R "${DAPPER_UID}:${DAPPER_GID}" . || true' exit
fi

mkdir -p bin dist
if [ -e ./scripts/$1 ]; then
    ./scripts/"$@"
else
    "$@"
fi
